### ISSUE TITLE
Use new archive/ top-level media type?

### ISSUE THREAD

**Issue by stain** [w3ctag/packaging-on-the-web#13]
A new IETF working group [arcmedia](https://www.ietf.org/mailman/listinfo/arcmedia) is forming, [proposing the top-level media-type archive/](https://tools.ietf.org/html/draft-seantek-kerwin-arcmedia-type). 

Should Packaging-on-the-web register as the media type `archive/package` instead of `application/package`? I would argue yes - if you intend for a package to be browsable as an archive.

It might be beneficial for Packaging-on-the-web folks to join the [arcmedia mailing list](https://www.ietf.org/mailman/listinfo/arcmedia).

Related to #11.

**Comment by JeniT** [comment]
Noted, thanks. It will depend on timing of the specs.
