### ISSUE TITLE
Zip CAN be streaming

### ISSUE THREAD

**Issue by stain** [w3ctag/packaging-on-the-web#14]
It is wrongly argued in https://github.com/w3ctag/packaging-on-the-web#zip-as-a-packaging-format that:

> The TAG discussed the use of zipped files as a packaging format. The main problem with using zips is that the central directory record, which lists the valid files within the zip archive, appears at the end of the zip. Implementations therefore need to wait until the whole zip is downloaded before the files within it can be read. This makes it unsuitable for a packaging format for efficient delivery of content on the web (the first of the requirements described above).

ZIP-files also start each file with a ZIP Entry. So there is no need for the central directory for anything except for knowing that there are no more files.

https://gist.github.com/stain/46dd33fb49e843d333bd is an example in Java where a file is written each second.

**Comment by slightlyoff** [comment]
Hey @stain: 

You're right that the argument is weak.

We did discuss the possibility of using per-entry file information instead of waiting for the CDR and decided that you _could_ use zip as a streaming format but that it probably wasn't a great fit for other reasons -- notably that we need headers to preserve the security properties for CSS and SVG content.

The text should change; will get that done.

**Comment by stain** [comment]
OK :) Although I might disagree with the assumption that the CDR would not match the file entries - it's quite tricky to do such a mistake - and as such it is just as likely to become a mistake in say your `rel=describedby` to point to a file that is not included, or for SPF to end early.

In http://w3ctag.github.io/packaging-on-the-web/#parts you say

> It is possible for multiple parts within a package to have the same part URL, either because they have exactly the same Content-Location header or because their Content-Location headers resolve to the same URL. Parts with the same part URL SHOULD be distinguishable by having different values for other headers commonly used for content negotiation, such as Content-Type or Content-Language. When these headers are used to distinguish between parts, they SHOULD be listed within the Vary header for the parts that share the same part URL. For example: 

Supporting this kind of content-negotiation-overloading  I think is a stronger argument against ZIP in packaging-on-the-web usecase - this would have to solved using a separate manifest or similar in a ZIP scenario (as we do in our [RO Bundle](https://w3id.org/bundle/#manifest-aggregates) with a `mediatype` entry combined with a `retrievedFrom`).
