### ISSUE TITLE
Is it safe to deploy over plain-text HTTP?

### ISSUE THREAD

**Issue by yoavweiss** [w3ctag/packaging-on-the-web#19]
Quoting from the document:

> Developers who cannot yet use HTTP/2 may find that using packages can provide performance benefits through reducing numbers of requests

I think there's an assumption here that this file format is safe to deploy over plain-text HTTP (Since TLS is probably the main hurdle to adoption of HTTP/2).

Since this format enables cache population under a certain path, is it not something we know to be safe to use with HTTP? Can't it be abused, beyond the current possible abuse of HTTP cache in MITM scenarios?

I think it'd be good if the document addressed that point.

**Comment by WebAppsWG** [comment]
Well, if you serve via http a package of content available via http, you gain or lose nothing, as everything can be MiTMed, serving over http a package of content available via https would be like shooting yourself in the foot, and so obviously that extra text is not needed here.

**Comment by ylafon** [comment]
Well, if you serve via http a package of content available via http, you gain or lose nothing, as everything can be MiTMed, serving over http a package of content available via https would be like shooting yourself in the foot, and so obviously that extra text is not needed here.

**Comment by yoavweiss** [comment]
Specifically what worries me is the package's ability to populate caches for URLs that the user has not (yet?) requested, and poison the user's cache.

I'm not sure there's a vulnerability there beyond MITMing simple HTTP traffic, but I think it's a point worth addressing, and getting a proper security review on.

**Comment by ylafon** [comment]
It shouldn't happen with general caches, but it might be with specialized caches (thinking of ServiceWorkers, for instance). I am closing this issue as populating caches is tracked in issue #10 but feel free to reopen if you think that the special case of using plain HTTP deserve a specific issue.
