### ISSUE TITLE
Caching and delta updates to packages

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/packaging-on-the-web#3]
It would be great if the document could speak more clearly (maybe it's own section) on how caching works and how updates to particular resources could happen. 

Like, if I send a package that contained my sites logo + 50 other files, but then I only update my logo, does the user need to re-download the whole package? What happens if I decide to remove a file for a package or add some new files, etc.

**Comment by JeniT** [comment]
In the newly created draft specification at http://w3ctag.github.io/packaging-on-the-web I've included a specific scenario based on caching semantics, which talks about the use of cache control headers at the level of the package and of the individual parts within the package. Feel free to reopen if you think the caching story is still unclear.
