### ISSUE TITLE
Please "un-gut" this specification

### ISSUE THREAD

**Issue by BigBlueHat** [w3ctag/packaging-on-the-web#35]
The last commit "gutted" this draft specification: https://github.com/w3ctag/packaging-on-the-web/commit/65af2845bf521f09f586df674522f62394de636c

While I understand that [WebPackage](http://github.com/wicg/webpackage) covers a similar topic area and list of use cases, it removes several features (human legibility, streaming, internal references via fragment identifiers) which are still of interest to the Publishing WG and possibly others.

"Gutting" any specification in this way also hampers discussion by breaking links and hiding the actual spec behind a "wall".

Please reconsider this approach and revert this commit: https://github.com/w3ctag/packaging-on-the-web/commit/65af2845bf521f09f586df674522f62394de636c

Thank you!
🎩

**Comment by swickr** [comment]
When work ceases on a spec I think it can be up to the discretion of the group to decide what to do with the content of the editor's draft.  However, I agree with @BigBlueHat that the version on w3.org/TR should not be eviscerated in this same way.   Rather, a new /TR version can be published with an additional subtitle saying "Obsoleted on yyyy-mm-dd", a stylesheet that flags it as an obsolete document, and text in the SoTD describing the (then) current state of the work.

**Comment by BigBlueHat** [comment]
@ylafon any thoughts on this? I'd very much like to see this spec "ungutted" and put back into a state where it can be researched and referenced during discussion.

Also, here is a much cleaner way to handle obsolescence: https://www.w3.org/TR/epr/

Thanks!

**Comment by plehegar** [comment]
@BigBlueHat yes, we're going to restore the content of the document. Just working on the details of the proper way to show it.

**Comment by slightlyoff** [comment]
Hey all,

It doesn't appear that there's implementer appetite to move forward with the design as it was outlined in this repo. If those missing features are needed, I recommend advocating for them over in the Web Packaging repo where I know @jyasskin et. al. are very much looking for use-cases and want to understand developer needs.

Regards

**Comment by BigBlueHat** [comment]
@slightlyoff this request and the related PR #36 from @plehegar is about fixing the "gutting" situation--not about the status of any in-progress or past attempts at Web Packaging.

The "gutting" of specifications (which has also happened elsewhere) is more confusing and troublesome than the "obsoleted" language used in @plehegar's PR.

One of the ways this "gutting" inhibits progress is that it breaks all past-URLs that point to portions of that specification--which we have done and are doing within the Publishing WG as we explore past, present, and in-progress packaging related specifications.

Please reopen this issue and merge PR #36. Thanks.

**Comment by marcoscaceres** [comment]
> The "gutting" of specifications (which has also happened elsewhere) is more confusing and troublesome than the "obsoleted" language used in @plehegar's PR.

Respectfully, I  disagree with this. Specs change/evolve over time and a large proportion of them "die on the vine". And, although burdensome, it's the Editor's responsibility to update broken links (that's the nature of the web, we deal with it). It's why we've been unapologetically gutting specs at the w3c for years.
  
>  Publishing WG as we explore past, present, and in-progress packaging related specifications

Ideally, the WG  should be tracking latest efforts, and updating whatever documents currently point to obsoleted things (to not point to them). 

Note that this specification didn't stop, it morphed into the other specification. The right solution here would have been for the TAG to have given this repository to the WICG, then there would have been a clear migration strategy/story (it helps avoid these kinds of situations).

**Comment by BigBlueHat** [comment]
@marcoscaceres "obsoleting" is much simpler, more obvious, and less cumbersome than "gutting" and ultimately makes research of past efforts made by the W3C much more explore-able--which is useful for innovate progress.

Additionally, it is still not clear that Google's Web Packaging format provides an equivalent feature set, and consequently there is still value and interest in exploring all the options possible and especially those previously considered.

**Comment by BigBlueHat** [comment]
> The right solution here would have been for the TAG to have given this repository to the WICG, then there would have been a clear migration strategy/story (it helps avoid these kinds of situations).

FWIW, I'd not be opposed to this even now. The TAG's Packaging on the Web spec will need to be re-licensed, however, as it's under the "old" document license--which prohibits "forking" or external progress made on a spec. If it were relicensed, then the WICG or another CG or WG could iterate on the work and more easily do a comparative analysis of the pros and cons between Google's approach, this approach, and various other Web-focused packaging specs.

I've found https://www.w3.org/2014/12/relicense.html but would need support of the TAG and/or a WG (Publishing, probably) to help move this to a place it could be iterated on further.

There is still valuable content in this specification that differs (now rather significantly) from it's "successor" and so, consequently, there's room (and need) for its reconsideration.

Regardless, gutting is still an offensive habit and marking things is obsolete is sufficient--when there is not an actual iterative process in place (such as continuing work at the WICG or elsewhere).

@swickr @plehegar if possible, it would still be helpful to have this specification (and others) ungutted, as well as re-licensed to encourage more participation and exploration of the options available on the Open Web Platform.

**Comment by jyasskin** [comment]
Note that there's a clear link to the [last version of the TAG's packaging proposal](https://www.w3.org/TR/2015/WD-web-packaging-20150115/) at the bottom of https://w3ctag.github.io/packaging-on-the-web/.

If the specification had been migrated to the WICG, you'd also have to click on a "previous versions" link to get back to the version with the features you want, and the links wouldn't have been preserved, so I don't think that's the option @BigBlueHat wants. I have no objections to re-adding the body content; I haven't gotten any complaints from people confused by which packaging proposal is current since 515ac901c321f89abd79b1070b8fd0279c0dbf7e.
