### ISSUE TITLE
Package Contents Header Field?

### ISSUE THREAD

**Issue by dret** [w3ctag/packaging-on-the-web#5]
interesting stuff! did you consider having a specific header field for listing the package's contents in the HTTP response? i haven't thought through this completely, and maybe it is subject to the same objections that you're listing for adding other HTTP-level constructs (such as a new status code), but for now i am just wondering if that might be another possibility for how to expose the contents of a package. In essence, it would lift packaging to being an HTTP-level mechanism, instead of just being a new media type.

**Comment by JeniT** [comment]
HTTP/2 Server Push already does packaging at the HTTP level, doesn't it? The spec at http://w3ctag.github.io/packaging-on-the-web is more detailed now. It includes using a `scope` property on links to the package to give a hint about its contents. We wanted to keep this relatively lightweight. Feel free to reopen if you feel there's more that could be done here.

**Comment by dret** [comment]
whatever HTTP/2 is doing, it might be useful to think through HTTP/1.1 scenarios as well. and maybe listing "contents" is a bad idea as something on the HTTP level. i was mostly curious if that was something you considered and then decided to exclude (for example because it might consume too much bandwidth to include those potentially large lists of URIs).
