### ISSUE TITLE
maybe use EPUB as a scenario?

### ISSUE THREAD

**Issue by dret** [w3ctag/packaging-on-the-web#6]
maybe it would be interesting to look at ebooks and EPUB in particular as a popular use case? after all, ebooks benefit a lot from packaging. but the web would benefit from this packaging being more open/standardized so that web architecture is able to reach into ebooks, and not just to their packaged level.

**Comment by JeniT** [comment]
Thanks, I've included a mention of that in the proper draft at http://w3ctag.github.io/packaging-on-the-web. Feel free to reopen if you think it would make sense to include a more detailed scenario. It would be useful if you also outlined what that scenario might be!

**Comment by dret** [comment]
maybe this is complicating things too much, but looking at the web arch level, it seems that any packaging runs the risk of "hiding resources" with a two-level addressing scheme. to some extent, web arch has inter- and intra-level addressing concepts with URIs and fragments. packaging breaks that a little bit. ebooks have a lot of interesting annotation examples (in particular when you look at shared settings and not just delivery to your kindle), and then the question is how to best balance stable resource identifiers, efficient packaging mechanisms, and resource fragment identification schemes. i am not claiming at all that i have good and/or easy answers for this, i am just saying that this is a general problem that might be good to address explicitly, both in terms of scenarios, and in terms of explaining how it fits into the bigger web arch picture.
