### ISSUE TITLE
tarballs

### ISSUE THREAD

**Issue by max-mapper** [w3ctag/packaging-on-the-web#7]
Hi, just wondering if there was a discussion about the tarball format. 

From the README:

```
The main problem with using zips is that the central directory record, which lists the valid files within the zip archive, appears at the end of the zip. 
```

Tarballs are stream friendly where ZIPs aren't, so this issue wouldn't apply

**Comment by JeniT** [comment]
We haven't discussed it, but it did occur to me. However, the issue about the restricted ability to include metadata about the parts of the package apply to TARs as well as ZIPs. Working through the example scenarios that I've put in http://w3ctag.github.io/packaging-on-the-web/ make me think that the ability to add HTTP headers for the individual parts of a package _for the web_ are just as important as the ability in TAR files to include information about the owner user/group.

That doesn't prevent TARs from being used as packages and linked to with `rel=package`, it just means that I still think the `application/package` format is a useful one.

**Comment by max-mapper** [comment]
ahh, yes, great points. +1
